### ISSUE TITLE
Maintainance Of This Project

### ISSUE THREAD

**Issue by aolszowka** [Evengard/MsBuildToCCNet#1]
Hi,

Your GitHub repository of this project is the first result I found in Google. Thank you for cloning this important project.

My company utilizes this logger extensively for our Internal CI System (which is quite large ~25 active releases). Therefore we have a vested interest in ensuring that this is maintained.

Recently we believe we've encountered a bug where this appears to fall apart when you tell MSBuild to build multi-cpu (/m). The behavior appears to report errors in the wrong projects which is not good. We're taking a stab at repairing the issue and we'll commit back the changes shortly (we stake no claim to the changes and would love to give back to a project that has helped us so much).

We've sent a message to the original owner (Christian Rodemeyer) to see if he'd like to put this up on GitHub himself to coordinate changes for the good of the entire community, but until we hear back we'll submit  pull requests to your repo.

Thank you,
Ace Olszowka

**Comment by Evengard** [comment]
No problem, I'm monitoring it. If the original author is going to create his repo I'll just fork from him and delete this one though most probably. If not - all your changes are welcomed here.

**Comment by aolszowka** [comment]
Thank you.

I took a stab at it last night; and was overwhelmed at first, so ended up implementing much of the project. However the end result ended up very similar to the original project (something about once you have to implement it yourself the original design makes way more sense). I created a new GitHub Repository here https://github.com/aolszowka/MsBuildToCCNetvNext along with a description of the changes.

The source is GPL'd so if we want to attempt a reintegration we could.

For those interested, the root cause of the problem is the existing project utilizes a Stack Queue based on project start, however when /m (multi-cpu) is passed the order in which these events arrive to the logger is not guaranteed.
